### ISSUE TITLE
Twice the size!

### ISSUE THREAD

**Issue by gyutw** [Utappia/cpanel-full-files-DB-backup#1]
Hi,
I just tested the database backup script and its FTP upload feature. The DB backup was successfully made and uploaded but the file size is twice the manual DB backup size!
Check this:
http://puu.sh/xZwXm/873de2bd8a.png

Left is the result from your script and left is the backup I made manually from them Cpanel backup option.

**Comment by medicamin** [comment]
I do have the same resaults. But after I imported the doubled size sql to a database, the resalut was the same as the original db and the parent script worked well without issue.

**Comment by gyutw** [comment]
Seems the developer abandoned this project.

**Comment by medicamin** [comment]
please test and upload the doubled size database, so as to confirm there is no issue with that. I've tested myself and didn't have any problem. 
This is the only working script I've found  for remote db backup.

**Comment by gyutw** [comment]
As it's a production server, I can not risk it.

**Comment by cerebrux** [comment]
@gyutw it is the same, un-compressed databes. Hence the difference in file size
